### ISSUE TITLE
aggressive retention purge

### ISSUE THREAD

**Issue by gsmol** [postgrespro/pg_probackup#106]
With WINDOW retention policy the purge is deleting ERROR backups because of reliance on recovery_time attribute, which is not initialized in ERROR backups.

**Comment by gsmol** [comment]
tests:
```
======================================================================
FAIL: test_window_error_backups_2 (tests.retention.RetentionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/retention.py", line 1366, in test_window_error_backups_2
    self.assertEqual(len(self.show_pb(backup_dir, 'node')), 3)
AssertionError: 2 != 3

======================================================================
FAIL: test_window_error_backups_1 (tests.retention.RetentionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/retention.py", line 1323, in test_window_error_backups_1
    self.assertEqual(len(self.show_pb(backup_dir, 'node')), 4)
AssertionError: 3 != 4
```

**Comment by gsmol** [comment]
Reported by Alex Ignatov.

**Comment by gsmol** [comment]
Merged to master.
