### ISSUE TITLE
parent choosing

### ISSUE THREAD

**Issue by gsmol** [postgrespro/pg_probackup#289]
check that full backup exists at all in instance list, before starting to wait for WAL
```
#0  0x00007f87219d4a04 in __GI___nanosleep (requested_time=requested_time@entry=0x7ffea674f840, remaining=remaining@entry=0x7ffea674f840) at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007f87219d490a in __sleep (seconds=0, seconds@entry=1) at ../sysdeps/posix/sleep.c:55
#2  0x00005625c64705be in wait_wal_lsn (target_lsn=28554821672, is_start_lsn=is_start_lsn@entry=true, tli=19, in_prev_segment=in_prev_segment@entry=false, segment_only=segment_only@entry=true, timeout_elevel=timeout_elevel@entry=1, in_stream_dir=false) at src/backup.c:1397
#3  0x00005625c6472677 in do_backup_instance (backup_conn=backup_conn@entry=0x5625c7a4b7b0, nodeInfo=nodeInfo@entry=0x7ffea6751eb0, no_sync=no_sync@entry=false, backup_logs=backup_logs@entry=false) at src/backup.c:157
#4  0x00005625c64736b6 in do_backup (start_time=1608736083, set_backup_params=0x0, no_validate=<optimized out>, no_sync=<optimized out>, backup_logs=<optimized out>) at src/backup.c:829
#5  0x00005625c6460f71 in main (argc=<optimized out>, argv=0x7ffea6752588) at src/pg_probackup.c:811
```

```
===========================================================================================================================
 Instance   Version  ID      Recovery Time  Mode  WAL Mode  TLI      Time  Data  WAL  Zratio  Start LSN   Stop LSN  Status
============================================================================================================================
 exampledb  ----     QLSUC8  ----           PAGE  ARCHIVE   0/0    1m:11s     0    0    1.00  0/0         0/0       RUNNING
 exampledb  ----     QLSU7P  ----           PAGE  ARCHIVE   0/0    3m:54s     0    0    1.00  0/0         0/0       RUNNING
 exampledb  ----     QLSSPF  ----           PAGE  ARCHIVE   0/0   36m:28s     0    0    1.00  0/0         0/0       RUNNING
 exampledb  11       QLSS7B  ----           PAGE  ARCHIVE   19/0       1s     0    0    1.00  6/A3000028  0/0       ERROR
 ```

**Comment by gsmol** [comment]
Merged.
