### ISSUE TITLE
Merge of compressed and uncompressed backup is failing

### ISSUE THREAD

**Issue by gsmol** [postgrespro/pg_probackup#38]
ERROR: test_merge_compressed_and_uncompressed_backups (tests.merge.MergeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/merge.py", line 301, in test_merge_compressed_and_uncompressed_backups
    self.merge_backup(backup_dir, "node", page_id)
  File "tests/helpers/ptrack_helpers.py", line 680, in merge_backup
    return self.run_pb(cmd_list + options, async, gdb, old_binary)
  File "tests/helpers/ptrack_helpers.py", line 583, in run_pb
    raise ProbackupException(e.output.decode("utf-8"), self.cmd)
ProbackupException: 
 ERROR: u'INFO: Merge started\nINFO: Merging backup PJCT5X with backup PJCT52\nINFO: Validating backup PJCT52\nINFO: Backup PJCT52 data files are valid\nINFO: Validating backup PJCT5X\nINFO: Backup PJCT5X data files are valid\nINFO: Delete: PJCT5X 2018-12-07 09:39:36+03\nINFO: Rename PJCT52 to PJCT5X\nINFO: Merging backup PJCT6S with backup PJCT5X\nINFO: Validating backup PJCT6S\nINFO: Backup PJCT6S data files are valid\nWARNING: An error occured during decompressing block 0 of file "/home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/merge/test_merge_compressed_and_uncompressed_backups/backup/backups/node/PJCT5X/database/base/13245/16387": Invalid compression algorithm\nERROR: page of file "/home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/merge/test_merge_compressed_and_uncompressed_backups/backup/backups/node/PJCT5X/database/base/13245/16387" uncompressed to -1 bytes. != BLCKSZ\nERROR: Data files merging failed\n'
 CMD: ['/home/gsmol/git/postgres/contrib/pg_probackup/pg_probackup merge -B /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/merge/test_merge_compressed_and_uncompressed_backups/backup --instance=node -i PJCT6S']

Looks like merge tries to decompresse file from not compressed backup.

**Comment by gsmol** [comment]
Fixed in 23d1a26e024
