### ISSUE TITLE
[bug] PG11 group access

### ISSUE THREAD

**Issue by gsmol** [postgrespro/pg_probackup#67]
`restore` do not set correct group permissions for restored directories of backup, taken from instance which was initialized with `--allow-group-access`

```
======================================================================
FAIL: test_pg_11_group_access (tests.restore.RestoreTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/restore.py", line 2192, in test_pg_11_group_access
    self.compare_pgdata(pgdata, pgdata_restored)
  File "tests/helpers/ptrack_helpers.py", line 1407, in compare_pgdata
    self.assertFalse(fail, error_message)
AssertionError: Restored PGDATA is not equal to original!

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/base/13321 Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/base/13321 Permissions: 16832

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/pg_multixact/members Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/pg_multixact/members Permissions: 16832

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/global Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/global Permissions: 16832

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/base/13320 Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/base/13320 Permissions: 16832

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/pg_multixact/offsets Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/pg_multixact/offsets Permissions: 16832

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/base/1 Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/base/1 Permissions: 16832

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/pg_replslot Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/pg_replslot Permissions: 16832

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/pg_stat Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/pg_stat Permissions: 16832

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/pg_xact Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/pg_xact Permissions: 16832

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/pg_serial Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/pg_serial Permissions: 16832

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/pg_snapshots Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/pg_snapshots Permissions: 16832

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/pg_dynshmem Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/pg_dynshmem Permissions: 16832

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/pg_commit_ts Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/pg_commit_ts Permissions: 16832

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/pg_tblspc Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/pg_tblspc Permissions: 16832

Dir permissions mismatch:
 Dir old: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node/data/pg_twophase Permissions: 16872
 Dir new: /home/gsmol/git/postgres/contrib/pg_probackup/tests/tmp_dirs/restore/test_pg_11_group_access/node_restored/data/pg_twophase Permissions: 16832
```

**Comment by gsmol** [comment]
Looks like problem is here:
https://github.com/postgrespro/pg_probackup/blob/master/src/dir.c#L904

We trust permissions from actual directory in `database`, not permission mask from `backup_content.control`

**Comment by gsmol** [comment]
I think current method of creating directories in create_data_directories() is awful.
Basically, we recreate existing directories from `database/` directory, despite the fact that we have a `backup_content.control` with all information we need.

**Comment by gsmol** [comment]
PR https://github.com/postgrespro/pg_probackup/pull/77
